### ISSUE TITLE
Generate Root Bone error location: <unknown location>:-1

### ISSUE THREAD

**Issue by fenpaws** [vini-guerrero/godot_game_tools#48]
After i try to get get a Root Bone I get that error, what exactly is the issue?

```python
Python: Traceback (most recent call last):
  File "/Users/soxx/Library/Application Support/Blender/2.93/scripts/addons/src/operators/rootmotion_controller.py", line 322, in execute
    fCurveBone = channel.data_path.split('"')[1]
IndexError: list index out of range

location: <unknown location>:-1
```

<img width="1792" alt="grafik" src="https://user-images.githubusercontent.com/29946173/133738915-3be51da1-1f8e-42ed-9f3e-dea3bd47b1d8.png">

When i look into the ARmature i can see the root bone but is a strange direction, and after i import that into Godot and set everything up to use the root bone it just played the animation normally without the correction from the engine.

<img width="1792" alt="grafik" src="https://cdn.discordapp.com/attachments/732288982691348601/888188378594549840/unknown.png">

**Comment by fenpaws** [comment]
Also here is the log, i added the `Channel:` so I would get whats inside the `channel.data_path`. It seams that Blender only returns `location`, so your next steps fail because of that.

```python
Import finished.
Info: Character Bones Successfully Renamed
Info: Rig Armature Prepared
Info: Root Bone Added
Channel: location
Python: Traceback (most recent call last):
  File "C:\Users\SoXX\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\src\operators\rootmotion_controller.py", line 323, in execute   
    fCurveBone = channel.data_path.split('"')[1]
IndexError: list index out of range

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\SoXX\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\src\operators\rootmotion_controller.py", line 323, in execute   
    fCurveBone = channel.data_path.split('"')[1]
IndexError: list index out of range

location: <unknown location>:-1
```

**Comment by fenpaws** [comment]
So It happens because I use my own rig that I made, Mixamo doesn't have a problem with it but it seems that your Addon has. Is there a way to fix that?

**Comment by phaitonican** [comment]
same error
