### ISSUE TITLE
Can't export character on V2.0.5 

### ISSUE THREAD

**Issue by Coregod360** [vini-guerrero/godot_game_tools#57]
Switched over to V2.0.5 to fix the single mesh error but now exporting gives the following error

` 
Python: Traceback (most recent call last):
  File "/home/user/.config/blender/3.1/scripts/addons/src/operators/export_character_controller.py", line 69, in execute
    bpy.ops.wm_ggt.push_nlas('EXEC_DEFAULT')
  File "/usr/share/blender/3.1/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/user/.config/blender/3.1/scripts/addons/src/operators/export_character_controller.py", line 42, in execute
    track.strips.new(action.name, start, action)
TypeError: NlaStrips.new(): error with argument 2, "start" -  Function.start expected an int type, not float

location: /usr/share/blender/3.1/scripts/modules/bpy/ops.py:130

location: <unknown location>:-1

`

Tried different models and animations but cant get it to work.

**Comment by andreami** [comment]
Will be solved with this https://github.com/vini-guerrero/godot_game_tools/pull/65 :)
